version: '2'
services:
  app:
    image: docker.io/bitnami/codeigniter:3
    ports:
      - '8000:8000'
    environment:
      CODEIGNITER_PROJECT_NAME: survey
    volumes:
      - '.:/app'
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.3
    environment:
      - MYSQL_DATABASE=bitnami_app
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=bn_app
      - MYSQL_PASSWORD=9rLCqkCf5Z
    volumes:
      - "./data/db/mysql:/var/lib/mysql"

